/// Flutter button_icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family: vinylicon
///      fonts:
///       - asset: fonts/vinylicon.ttf
///
/// 
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
///
import 'package:flutter/widgets.dart';

class VinylIcon {
  VinylIcon._();

  static const _kFontFam = 'VinylIcon';
  static const String? _kFontPkg = null;

  static const IconData cd = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
